### ISSUE TITLE
Make a manager command for the tests instead of using a separate module

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/airtng-flask#1]
Instead of using a separate `test.py` module, we should run the tests through the `manage.py` module instead.

Here's a good example: https://github.com/atbaker/anti-voicemail/blob/master/manage.py#L19-L24

So when you're done, the new test command will look like `coverage run manage.py test`. You should update the `.travis.yml` file and the README to use that new command, and then delete the `test.py` module.

**Comment by nebtrx** [comment]
Regarding this, I did separate those concerns in order to be able to load test environments vars, because I need to load dev environments var inside manager to be able to perform the migration.

**Comment by atbaker** [comment]
I see. In that case, I would still add the tests to the management command, but just call `get_app` again to get the Flask app with the testing configuration.

Maybe something like this?

```
@manager.command
def test():
    """Run the unit tests."""
    # Get the app, this time with the test config
    app = get_app('test')

    # Run the tests
    import unittest
    tests = unittest.TestLoader().discover('tests')
    unittest.TextTestRunner(verbosity=2).run(tests)
```

In the next app, we should make the `manage.py` work with any configuration by structuring it more like this: 

https://github.com/atbaker/anti-voicemail/blob/master/manage.py#L8

**Comment by nebtrx** [comment]
Ok that should work, I was thinking in keeping a single app object following the lead. I'll take a look on the code you've just provide follow that approach in the future .
