### ISSUE TITLE
Use SQLAlchemy's db.Enum field for Reservation.status

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/airtng-flask#2]
Right now the app uses a separate class called `ReservationStatus` to keep track of the possible values for the `Reservation.status` field.

This is unnecessary - we should just use SQLAlchemy's built-in `Enum` feature for this instead:

http://docs.sqlalchemy.org/en/latest/core/type_basics.html#sqlalchemy.types.Enum

I would add some constants to the top of the `Reservation` class and then do something like this:

```
class Reservation(db.Model):
    __tablename__ = "reservations"

    # Status constants
    PENDING = 'pending'
    CONFIRMED = 'confirmed'
    REJECTED = 'rejected'

    ...

    status = db.Column(db.Enum(PENDING, CONFIRMED, REJECTED, name='reservation_status_enum', default=PENDING))
```

**Comment by jarodreyes** [comment]
+1

**Comment by nebtrx** [comment]
Done!
