### ISSUE TITLE
Remove SmsNotifier service and put those methods on the models instead

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/airtng-flask#3]
In Python, we prefer to add methods to our Models instead of breaking them out into separate utilities or services. We often say the phrase "Fat models are a good thing."

Let's remove the SmsNotifier class, and instead add its methods to the `Reservation` method instead.

**Edit:** We should also remove the `SmsSender` class and include its logic in these new model methods. I prefer not to make a new class, utility, or service if it's only going to be used in one place, which is the case with `SmsSender`.

**Comment by nebtrx** [comment]
OK no problem doing that. The idea behind that particular example was following responsibility principle to show/encourage correctness and the use of SOLID practices
