### ISSUE TITLE
Remove StringBuilder class and use templates instead

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/airtng-flask#4]
One of the nice things about Flask's template engine is that you can use it for any text - not just HTML.

Let's remove the `StringBuilder` class and instead make templates that render those messages. Here's how I would do it:

1. Make a new directory inside `airtng_flask/templates` called `messages`
1. Create two files in there: `reservation_request.txt` and `reservation_confirmation.txt`
1. Where you call `StringBuilder` right now, instead use Flask's `render_template` function and with the variables you need

You can see an example here:

- Text message template: https://github.com/atbaker/anti-voicemail/blob/master/app/templates/voice/new_voicemail.txt
- Rendering the template in a model method: https://github.com/atbaker/anti-voicemail/blob/master/app/models.py#L209-L220

**Comment by nebtrx** [comment]
Done!
