### ISSUE TITLE
Avoid use of global variables whenever possible

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/airtng-flask#6]
In Python, we very rarely use global variables. I spotted a global variable on this line:

https://github.com/TwilioDevEd/airtng-flask/blob/master/airtng_flask/views.py#L104

Do we really need this variable to be global? Is there any reason why it can't be local?

**Comment by nebtrx** [comment]
That was suggested by PyCharm, I read a little about that and it seemed kind of straight to me. I can remove it

**Comment by nebtrx** [comment]
Done
