### ISSUE TITLE
Path to sqlite db?

### ISSUE THREAD

**Issue by jonedavis** [TwilioDevEd/airtng-flask#73]
To confirm, do we instructions to fill out .env to path to sqlite file or is sqlite:// sufficient?

**Comment by po5i** [comment]
Actually this setting isn't even required since the path is hardcoded.

https://github.com/TwilioDevEd/airtng-flask/pull/61/files#diff-fa59bd3b08fbbc037c01717e802afddcL17

**Comment by jonedavis** [comment]
Cool, can we remove it from .env?
